# Generated by Django 4.1 on 2023-07-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_item', models.TextField(verbose_name='query_item')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
    ]
