# Generated by Django 4.1 on 2023-07-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftingcalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftingquery',
            name='user',
            field=models.IntegerField(default=1, verbose_name='uuid'),
            preserve_default=False,
        ),
    ]
