# Generated by Django 4.1 on 2023-07-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftingcalc', '0002_craftingquery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_use_craftingcalc', 'can_use_craftingcalc'),),
            },
        ),
    ]
